#include iostream;
using namespace std;

int main()
{
    int coffee;
    cout<<"Espresso,Americano,Cappuccino,Latte";
    switch(coffee){
        case 1;
        cout<< "Espresso";
        break;
        case 2;
        cout<<"Americano";
        break;
        case 3;
        cout<<"Cappuccino";
        break;
        case 4;
        cout<<"Latte";
        break;
        default;
        cout<<"cute mo hayop ka"
}
