#include <iostream>
using namespace std;

int main(); {
    int ( 1_espresso,2Americano,3Capuccino,4latte);
    cin >> coffee;
    switch (coffee) 
    {
    case '1':
    cout << ""espresso";
    break;
    case '2':
    cout <<  "Americano";
    break;
    case '3':
    cout << "Cappuccino";
    break;
    case '4':
    cout << "latte";
    break;
    default:

        break;
    }
  


}